### ISSUE TITLE
Add a usable memory driver

### ISSUE THREAD

**Issue by flimzy** [flimzy/kivik#142]
As this is a rather large project, and utility can be found (at least by me) prior to a complete feature, I decided to create this issue to track the ongoing progress toward a complete memory driver.

In rough order of priority, I wish to:

- [x] Allow creating and destroying databases
- [x] Allow storing, fetching and deleting documents (#141)
- [ ] Support attachments
- [ ] AllDocs
    - [x] Basic AllDocs queries (#148)
    - [ ] Support `conflicts`
    - [ ] Support `descending`
    - [ ] Support `endkey`, `startkey` and `inclusive_end`
    - [ ] Support `include_docs`
    - [ ] Support `keys`
    - [ ] Support `limit` (#167)
    - [ ] Support `skip`
    - [ ] Support `stale`
    - [ ] Support `update_seq`
- [x] BulkDocs (#158)
- [ ] Get/set Security
- [ ] Support Mango queries  (See also https://github.com/go-kivik/mango/milestone/1)
    - [x] Basic query support (#166)
    - [ ] Support `limit`
    - [ ] Support `skip`
    - [ ] Support `sort`
    - [x] Support `fields` (#169)
    - [ ] Support `use_index`
- [ ] Support Mango indexes
    - [ ] Create indexes
    - [ ] Query indexes
    - [ ] Delete indexes
- [ ] Support traditional views with indexes
- [ ] Support other traditional view functionality (reduce, list, etc)
- [ ] Changes feed
- [ ] Support replication

**Comment by flimzy** [comment]
Issue moved to new repo: https://github.com/go-kivik/memorydb/issues/2
