### ISSUE TITLE
Add support for CouchDB 2.1.0

### ISSUE THREAD

**Issue by flimzy** [flimzy/kivik#174]
CouchDB 2.1.0 was recently released. Kivik should support 2.1.0 fully. See [What's New in 2.1.0](http://docs.couchdb.org/en/2.1.0/whatsnew/2.1.html)

This is waiting on an official Docker image (see https://github.com/apache/couchdb-docker/issues/23).

The following CouchDB 2.1.0 changes may require changes in Kivik:

- [x] New replication scheduler [works out-of-box with work-around, #215 for complete fix]
- [x] Replication filter now supports using the body of the replication request for Mango queries.[COUCHDB-2988](https://issues.apache.org/jira/browse/COUCHDB-2988) [No change needed]
- [x] Add support for reporting Too Large errors. [COUCHDB-2992](https://issues.apache.org/jira/browse/COUCHDB-2992) [Added status code in #214]
- [x] “stale=ok” option replaced with new “stable” and “update” options. [COUCHDB-3036](https://issues.apache.org/jira/browse/COUCHDB-3063)  [No change needed]
- [x] New info in welcome message [COUCHDB-3180](https://issues.apache.org/jira/browse/COUCHDB-3180) [#214 & https://github.com/go-kivik/couchdb/pull/13 ]
- [x] OAuth1 support removed [Doc changes only, in #214]

Please add comments to this issue regarding any other relevant changes that should be made or considered for supporting CouchDB 2.1.0.

**Comment by flimzy** [comment]
At the moment, Kivik's replication appears to work with CouchDB 2.1 when [`update_docs`](http://docs.couchdb.org/en/2.1.0/config/replicator.html#replicator/update_docs) is true. This is considered a work-around, and #215 will track fixing this more completely.

**Comment by flimzy** [comment]
#215 has now been resolved, so I'm closing this issue.
